[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "backtester"
version = "0.0.0.9000"
dependencies = [
    "numpy",
    "pandas",
]

[project.optional-dependencies]
test = [
    "pytest"
]