name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '3.9'
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install pytest .
        
      - name: Run tests
        run: pytest




# name: Test package

# on:
#   push:
#     branches: [ master ]
#   pull_request: 
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.9
#       - name: Install testing dependencies 
#         run: python -m pip install themis/[test]
#       - name: Test themis package
#         run: pytest ./themis/tests/ -vv
